export type Board = { id: number; name: string };
export type Game = { slug: string; name: string; boards: Board[] };

export const GAMES: Game[] = [
  {
    slug: "maplestoryidle-kr",
    name: "메이플 키우기",
    boards: [
      { id: 6633, name: "공지사항" },
      { id: 6698, name: "패치노트" },
      { id: 6697, name: "이벤트" },
      { id: 6745, name: "확인 중인 현상" },
      { id: 6730, name: "FAQ" },
      { id: 6712, name: "버그/오류 제보" },
      { id: 6713, name: "튕김/끊김 제보" },
      { id: 6714, name: "신고 접수" },
    ],
  },
  {
    slug: "azurpromilia",
    name: "아주르 프로밀리아",
    boards: [
      { id: 6829, name: "전체 게시글 보기" },
      { id: 6808, name: "공지사항" },
      { id: 6809, name: "별의 기록" },
      { id: 6811, name: "진행 이벤트" },
      { id: 7008, name: "종료 이벤트" },
      { id: 7012, name: "당첨 안내" },
      { id: 6813, name: "캐릭터" },
      { id: 6814, name: "콘텐츠" },
      { id: 6815, name: "세계관" },
      { id: 6858, name: "아주르 갤러리" },
      { id: 6825, name: "자유게시판" },
      { id: 6827, name: "자주 묻는 질문(FAQ)" },
    ],
  },
  {
    slug: "bluearchive",
    name: "블루 아카이브",
    boards: [
      { id: 1080, name: "전체글보기" },
      { id: 1018, name: "공지사항" },
      { id: 1076, name: "업데이트" },
      { id: 1077, name: "개발자 편지" },
      { id: 1073, name: "상점 안내" },
      { id: 4606, name: "확률 안내" },
      { id: 1039, name: "진행 이벤트" },
      { id: 1040, name: "당첨 안내" },
      { id: 1053, name: "종료 이벤트" },
      { id: 1070, name: "공략 게시판" },
      { id: 1071, name: "게임 가이드" },
      { id: 1072, name: "자주 묻는 질문(FAQ)" },
      { id: 1050, name: "대나무숲(자유게시판)" },
      { id: 1079, name: "자랑 게시판" },
      { id: 1041, name: "친구 모집/서클 홍보" },
      { id: 1042, name: "2차 창작 아틀리에" },
    ],
  },
  {
    slug: "baramy",
    name: "바람의나라: 연",
    boards: [
      { id: 3706, name: "전체 게시글 보기" },
      { id: 259, name: "필독공지" },
      { id: 731, name: "패치노트" },
      { id: 743, name: "개발자 서신" },
      { id: 685, name: "진행 중 이벤트" },
      { id: 662, name: "바람:연 FAQ" },
      { id: 261, name: "자유게시판" },
      { id: 724, name: "지식공략" },
      { id: 725, name: "밸런스 토론" },
      { id: 684, name: "스샷/동영상" },
      { id: 740, name: "팬아트" },
      { id: 4429, name: "건의 접수" },
      { id: 4430, name: "버그/오류 제보" },
    ],
  },
  {
    slug: "fcmobile",
    name: "FC 모바일",
    boards: [
      { id: 441, name: "공지사항" },
      { id: 442, name: "점검/패치 안내" },
      { id: 445, name: "코치노트" },
      { id: 443, name: "이벤트 소식, 당첨발표" },
      { id: 447, name: "자유게시판" },
      { id: 448, name: "자랑게시판" },
      { id: 449, name: "선수 추천, 후기 게시판" },
      { id: 4443, name: "오류/버그 제보" },
      { id: 4444, name: "건의 접수" },
    ],
  },
  {
    slug: "kartrush",
    name: "카트라이더 러쉬플러스",
    boards: [
      { id: 785, name: "전체 글 보기" },
      { id: 839, name: "공지사항" },
      { id: 4494, name: "확인 중인 현상" },
      { id: 833, name: "GM 소식" },
      { id: 741, name: "이벤트&대회 공지" },
      { id: 895, name: "E스포츠 소식" },
      { id: 636, name: "묻고 답하기" },
      { id: 635, name: "카러플 공략" },
      { id: 546, name: "자유 게시판" },
      { id: 547, name: "클럽 게시판" },
      { id: 637, name: "스샷&영상 앨범" },
      { id: 3497, name: "버그(오류) 제보하기" },
      { id: 3499, name: "건의 접수하기" },
    ],
  },
  {
    slug: "v4kr",
    name: "V4",
    boards: [
      { id: 1367, name: "전체 글 보기" },
      { id: 1148, name: "공지사항" },
      { id: 1172, name: "업데이트 노트" },
      { id: 1173, name: "개발자 편지" },
      { id: 1174, name: "V4 상점 안내" },
      { id: 1175, name: "진행 이벤트" },
      { id: 1176, name: "당첨 안내" },
      { id: 1178, name: "자유 게시판" },
      { id: 1179, name: "건의 게시판" },
      { id: 1181, name: "나만의 공략&노하우" },
      { id: 1182, name: "길드 홍보&가입" },
      { id: 1184, name: "스크린샷 게시판" },
      { id: 4303, name: "튕김(끊김) 제보하기" },
      { id: 4304, name: "버그(오류) 제보하기" },
    ],
  },
];

export const GAME_MAP = Object.fromEntries(GAMES.map((g) => [g.slug, g]));
